---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: check-if-image-signed
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  background: false
  failurePolicy: Fail
  rules:
    - name: check-if-image-signed
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETBjpUH3c9jovTXOI+OqaZR/6NRpU
                fpM8XPosUdaC7gcUuPQ4p6hp3Plr2aH/M2p44t0aC4++QygpWS4L7btKDQ==
                -----END PUBLIC KEY-----

