FROM cgr.dev/chainguard/node:latest

WORKDIR /app

ENV NODE_ENV=production

COPY --chown=node:node /src/package.json /src/package-lock.json ./

RUN npm install

COPY --chown=node:node /src ./

ENTRYPOINT ["npm", "start"]
EXPOSE 5000
